### ISSUE TITLE
Example Implementation

### ISSUE THREAD

**Issue by capturemathan** [capturemathan/Gitcard#10]
Create an `example` folder implementing the library in popular languages like `ReactJS` 😉

**Comment by chinmaym07** [comment]
Hey @capturemathan  .Can you explain a little more about this. I want to give it a try.! :grinning:

**Comment by capturemathan** [comment]
> Hey @capturemathan .Can you explain a little more about this. I want to give it a try.! 😀

Hey @chinmaym07 , Create an example folder in the root directory. Then using REACT JS, implement the library by following the instructions in README. Need not worry about other details in the REACT Web Page just have a single page implementing this library.
