### ISSUE TITLE
Redefining Total Contributions Function

### ISSUE THREAD

**Issue by capturemathan** [capturemathan/Gitcard#4]
`totalContributions(username)` method needs to be rewritten using Plain JS instead of fetching from external API `https://mathanapis.000webhostapp.com/fetchcontrib.php` which is currently down :(

**Comment by pranshumaheshwari** [comment]
Is someone working on it or can I work on it.
It is easily solvable using the github api v4

**Comment by capturemathan** [comment]
> Is someone working on it or can I work on it.
> It is easily solvable using the github api v4

Yeah sure you can work on the issue :)

**Comment by capturemathan** [comment]
Thanks for your contribution 💯
