### ISSUE TITLE
Migrate from Hardcoded HTML

### ISSUE THREAD

**Issue by capturemathan** [capturemathan/Gitcard#6]
Replace the hardcoded HTML in `app.js` with external modules like `cheerio` to enhance readability and error detection in the future.

**Comment by mohas** [comment]
I can work on this but I recommend a template engine like pug, or mustache, lodash also has a templating functionality, so let me know, I personally recommend lodash  as it can be used for many many more functionalities

**Comment by capturemathan** [comment]
> I can work on this but I recommend a template engine like pug, or mustache, lodash also has a templating functionality, so let me know, I personally recommend lodash as it can be used for many many more functionalities

Thank you for your interest in this issue. I personally have very limited knowledge of using template engines and EJS was my go to guy when dealing with MERN stack. Can you work on this using EJS so that future maintenance can be easier :)

**Comment by mohas** [comment]
say no more, I will use lodash which uses roughly the same syntax as ejs

**Comment by mohas** [comment]
see my pull request I ended using string interpolation after a closer look at your code, I ended up rewriting nearly all the code to be more consistent with standards and more maintainable, did not test it tho

**Comment by capturemathan** [comment]
> see my pull request I ended using string interpolation after a closer look at your code, I ended up rewriting nearly all the code to be more consistent with standards and more maintainable, did not test it tho

Please attach a screenshot of the console O/P to ensure the working. Also after placing the screenshot, make sure to remove your github-token.
